"""Parity test: the Python pricing engine must reproduce, to the cent, the
premiums produced by the original legacy JavaScript engine
(``legacy/imoth_motor_quotation_reference.html``).

``fixtures/parity_vectors.json`` was generated by actually *running* the
legacy ``computePremium`` function in Node.js across every insurer/class,
a spread of Sum Insured values (band boundaries, mid-band, off-grid), every
vehicle-age bracket relevant to the >15yr private-vehicle EP/PVT rule, and
every combination of optional add-ons (EP, PVT, Political Violence &
Terrorism) plus the CIC Loss-Ratio toggle. See
``backend/tests/fixtures/README.md`` for regeneration instructions.
"""
import json
from pathlib import Path

import pytest

from app.seed.insurers_data import INSURERS, LEVY_RATE, STAMP_DUTY
from app.services.pricing_engine import compute_premium

FIXTURES_DIR = Path(__file__).parent / "fixtures"
VECTORS = json.loads((FIXTURES_DIR / "parity_vectors.json").read_text())


def _translate_opts(js_opts: dict) -> dict:
    return {
        "ep": js_opts.get("ep", False),
        "pvt": js_opts.get("pvt", False),
        "pv_terror": js_opts.get("pvTerror", False),
        "lr_band": js_opts.get("lrBand"),
        "pll_seats": js_opts.get("pllSeats", 0),
        "pll_option_key": js_opts.get("pllOptionKey"),
        "age": js_opts.get("age"),
    }


@pytest.mark.parametrize("vector", VECTORS, ids=lambda v: f"{v['insurer']}:{v['klass']}:si={v['si']}")
def test_matches_legacy_engine(vector):
    motor_class = INSURERS[vector["insurer"]]["classes"][vector["klass"]]
    opts = _translate_opts(vector["opts"])

    result = compute_premium(motor_class, vector["si"], opts, LEVY_RATE, STAMP_DUTY)

    assert result.subtotal == pytest.approx(vector["subtotal"], abs=0.01)
    assert result.levies == pytest.approx(vector["levies"], abs=0.01)
    assert result.total == pytest.approx(vector["total"], abs=0.01)


def test_vectors_loaded():
    assert len(VECTORS) > 1000
