"""add document_counters table

Revision ID: 3bd5c0b716ba
Revises: 71b4ca038499
Create Date: 2026-08-26 17:36:02.868427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd5c0b716ba'
down_revision: Union[str, None] = '71b4ca038499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type', 'year', name='uq_document_counter_type_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_counters')
    # ### end Alembic commands ###
