"""add client document uploads and acceptance statement flag

Revision ID: c2eaab00a7ed
Revises: 3bd5c0b716ba
Create Date: 2026-08-31 10:30:30.853626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2eaab00a7ed'
down_revision: Union[str, None] = '3bd5c0b716ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_document_uploads',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('LOGBOOK', 'NATIONAL_ID', 'KRA_PIN', name='required_document_type'), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REPLACED', 'REMOVED', name='client_upload_status'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_document_uploads_client_id'), 'client_document_uploads', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_document_uploads_document_type'), 'client_document_uploads', ['document_type'], unique=False)
    op.create_index(op.f('ix_client_document_uploads_quotation_id'), 'client_document_uploads', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_client_document_uploads_status'), 'client_document_uploads', ['status'], unique=False)
    op.add_column(
        'quotations',
        sa.Column('acceptance_statement_accepted', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('quotations', 'acceptance_statement_accepted', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'acceptance_statement_accepted')
    op.drop_index(op.f('ix_client_document_uploads_status'), table_name='client_document_uploads')
    op.drop_index(op.f('ix_client_document_uploads_quotation_id'), table_name='client_document_uploads')
    op.drop_index(op.f('ix_client_document_uploads_document_type'), table_name='client_document_uploads')
    op.drop_index(op.f('ix_client_document_uploads_client_id'), table_name='client_document_uploads')
    op.drop_table('client_document_uploads')
    # ### end Alembic commands ###
    sa.Enum(name='verification_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='client_upload_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='required_document_type').drop(op.get_bind(), checkfirst=True)
